import 'package:flutter/material.dart';

const kPrimaryColor = Colors.lightBlueAccent;
const kSecondaryColor = Colors.blueAccent;

const kTextInputDecoration = InputDecoration(
  contentPadding: EdgeInsets.symmetric(vertical: 10, horizontal: 20),
  enabledBorder: OutlineInputBorder(
    borderSide: BorderSide(width: 1, color: Colors.lightBlueAccent),
    borderRadius: BorderRadius.all(Radius.circular(30.0)),
  ),
  focusedBorder: OutlineInputBorder(
    borderSide: BorderSide(width: 2, color: Colors.lightBlueAccent),
    borderRadius: BorderRadius.all(Radius.circular(30.0)),
  ),
);

const logoImage = 'assets/images/logo.png';
const IconData sticker =
    IconData(0xe800, fontFamily: 'Sticker', fontPackage: null);

const ben = [
  'assets/stickers/ben/ben (1).png',
  'assets/stickers/ben/ben (10).png',
  'assets/stickers/ben/ben (11).png',
  'assets/stickers/ben/ben (12).png',
  'assets/stickers/ben/ben (13).png',
  'assets/stickers/ben/ben (14).png',
  'assets/stickers/ben/ben (15).png',
  'assets/stickers/ben/ben (16).png',
  'assets/stickers/ben/ben (17).png',
  'assets/stickers/ben/ben (18).png',
  'assets/stickers/ben/ben (19).png',
  'assets/stickers/ben/ben (2).png',
  'assets/stickers/ben/ben (20).png',
  'assets/stickers/ben/ben (21).png',
  'assets/stickers/ben/ben (22).png',
  'assets/stickers/ben/ben (23).png',
  'assets/stickers/ben/ben (24).png',
  'assets/stickers/ben/ben (25).png',
  'assets/stickers/ben/ben (26).png',
  'assets/stickers/ben/ben (27).png',
  'assets/stickers/ben/ben (28).png',
  'assets/stickers/ben/ben (29).png',
  'assets/stickers/ben/ben (3).png',
  'assets/stickers/ben/ben (30).png',
  'assets/stickers/ben/ben (31).png',
  'assets/stickers/ben/ben (32).png',
  'assets/stickers/ben/ben (33).png',
  'assets/stickers/ben/ben (34).png',
  'assets/stickers/ben/ben (35).png',
  'assets/stickers/ben/ben (36).png',
  'assets/stickers/ben/ben (37).png',
  'assets/stickers/ben/ben (38).png',
  'assets/stickers/ben/ben (39).png',
  'assets/stickers/ben/ben (4).png',
  'assets/stickers/ben/ben (40).png',
  'assets/stickers/ben/ben (5).png',
  'assets/stickers/ben/ben (6).png',
  'assets/stickers/ben/ben (7).png',
  'assets/stickers/ben/ben (8).png',
  'assets/stickers/ben/ben (9).png'
];

const little_girl = [
  'assets/stickers/little-girl/little-girl (1).png',
  'assets/stickers/little-girl/little-girl (10).png',
  'assets/stickers/little-girl/little-girl (11).png',
  'assets/stickers/little-girl/little-girl (12).png',
  'assets/stickers/little-girl/little-girl (13).png',
  'assets/stickers/little-girl/little-girl (14).png',
  'assets/stickers/little-girl/little-girl (15).png',
  'assets/stickers/little-girl/little-girl (16).png',
  'assets/stickers/little-girl/little-girl (17).png',
  'assets/stickers/little-girl/little-girl (18).png',
  'assets/stickers/little-girl/little-girl (19).png',
  'assets/stickers/little-girl/little-girl (2).png',
  'assets/stickers/little-girl/little-girl (20).png',
  'assets/stickers/little-girl/little-girl (21).png',
  'assets/stickers/little-girl/little-girl (22).png',
  'assets/stickers/little-girl/little-girl (23).png',
  'assets/stickers/little-girl/little-girl (24).png',
  'assets/stickers/little-girl/little-girl (25).png',
  'assets/stickers/little-girl/little-girl (26).png',
  'assets/stickers/little-girl/little-girl (27).png',
  'assets/stickers/little-girl/little-girl (28).png',
  'assets/stickers/little-girl/little-girl (29).png',
  'assets/stickers/little-girl/little-girl (3).png',
  'assets/stickers/little-girl/little-girl (30).png',
  'assets/stickers/little-girl/little-girl (31).png',
  'assets/stickers/little-girl/little-girl (32).png',
  'assets/stickers/little-girl/little-girl (33).png',
  'assets/stickers/little-girl/little-girl (34).png',
  'assets/stickers/little-girl/little-girl (35).png',
  'assets/stickers/little-girl/little-girl (36).png',
  'assets/stickers/little-girl/little-girl (37).png',
  'assets/stickers/little-girl/little-girl (38).png',
  'assets/stickers/little-girl/little-girl (39).png',
  'assets/stickers/little-girl/little-girl (4).png',
  'assets/stickers/little-girl/little-girl (40).png',
  'assets/stickers/little-girl/little-girl (5).png',
  'assets/stickers/little-girl/little-girl (6).png',
  'assets/stickers/little-girl/little-girl (7).png',
  'assets/stickers/little-girl/little-girl (8).png',
  'assets/stickers/little-girl/little-girl (9).png'
];

const cute_couple = [
  'assets/stickers/cute-couple/cute-couple (1).png',
  'assets/stickers/cute-couple/cute-couple (10).png',
  'assets/stickers/cute-couple/cute-couple (11).png',
  'assets/stickers/cute-couple/cute-couple (12).png',
  'assets/stickers/cute-couple/cute-couple (13).png',
  'assets/stickers/cute-couple/cute-couple (14).png',
  'assets/stickers/cute-couple/cute-couple (15).png',
  'assets/stickers/cute-couple/cute-couple (16).png',
  'assets/stickers/cute-couple/cute-couple (17).png',
  'assets/stickers/cute-couple/cute-couple (18).png',
  'assets/stickers/cute-couple/cute-couple (19).png',
  'assets/stickers/cute-couple/cute-couple (2).png',
  'assets/stickers/cute-couple/cute-couple (20).png',
  'assets/stickers/cute-couple/cute-couple (21).png',
  'assets/stickers/cute-couple/cute-couple (22).png',
  'assets/stickers/cute-couple/cute-couple (23).png',
  'assets/stickers/cute-couple/cute-couple (24).png',
  'assets/stickers/cute-couple/cute-couple (25).png',
  'assets/stickers/cute-couple/cute-couple (26).png',
  'assets/stickers/cute-couple/cute-couple (27).png',
  'assets/stickers/cute-couple/cute-couple (28).png',
  'assets/stickers/cute-couple/cute-couple (29).png',
  'assets/stickers/cute-couple/cute-couple (3).png',
  'assets/stickers/cute-couple/cute-couple (30).png',
  'assets/stickers/cute-couple/cute-couple (31).png',
  'assets/stickers/cute-couple/cute-couple (32).png',
  'assets/stickers/cute-couple/cute-couple (33).png',
  'assets/stickers/cute-couple/cute-couple (34).png',
  'assets/stickers/cute-couple/cute-couple (35).png',
  'assets/stickers/cute-couple/cute-couple (36).png',
  'assets/stickers/cute-couple/cute-couple (37).png',
  'assets/stickers/cute-couple/cute-couple (38).png',
  'assets/stickers/cute-couple/cute-couple (39).png',
  'assets/stickers/cute-couple/cute-couple (4).png',
  'assets/stickers/cute-couple/cute-couple (40).png',
  'assets/stickers/cute-couple/cute-couple (5).png',
  'assets/stickers/cute-couple/cute-couple (6).png',
  'assets/stickers/cute-couple/cute-couple (7).png',
  'assets/stickers/cute-couple/cute-couple (8).png',
  'assets/stickers/cute-couple/cute-couple (9).png'
];

const milk_mocha = [
  'assets/stickers/milk&mocha/milk&mocha (1).png',
  'assets/stickers/milk&mocha/milk&mocha (10).png',
  'assets/stickers/milk&mocha/milk&mocha (11).png',
  'assets/stickers/milk&mocha/milk&mocha (12).png',
  'assets/stickers/milk&mocha/milk&mocha (13).png',
  'assets/stickers/milk&mocha/milk&mocha (14).png',
  'assets/stickers/milk&mocha/milk&mocha (15).png',
  'assets/stickers/milk&mocha/milk&mocha (16).png',
  'assets/stickers/milk&mocha/milk&mocha (17).png',
  'assets/stickers/milk&mocha/milk&mocha (18).png',
  'assets/stickers/milk&mocha/milk&mocha (19).png',
  'assets/stickers/milk&mocha/milk&mocha (2).png',
  'assets/stickers/milk&mocha/milk&mocha (20).png',
  'assets/stickers/milk&mocha/milk&mocha (21).png',
  'assets/stickers/milk&mocha/milk&mocha (22).png',
  'assets/stickers/milk&mocha/milk&mocha (23).png',
  'assets/stickers/milk&mocha/milk&mocha (24).png',
  'assets/stickers/milk&mocha/milk&mocha (25).png',
  'assets/stickers/milk&mocha/milk&mocha (26).png',
  'assets/stickers/milk&mocha/milk&mocha (27).png',
  'assets/stickers/milk&mocha/milk&mocha (28).png',
  'assets/stickers/milk&mocha/milk&mocha (29).png',
  'assets/stickers/milk&mocha/milk&mocha (3).png',
  'assets/stickers/milk&mocha/milk&mocha (30).png',
  'assets/stickers/milk&mocha/milk&mocha (31).png',
  'assets/stickers/milk&mocha/milk&mocha (32).png',
  'assets/stickers/milk&mocha/milk&mocha (33).png',
  'assets/stickers/milk&mocha/milk&mocha (34).png',
  'assets/stickers/milk&mocha/milk&mocha (35).png',
  'assets/stickers/milk&mocha/milk&mocha (36).png',
  'assets/stickers/milk&mocha/milk&mocha (37).png',
  'assets/stickers/milk&mocha/milk&mocha (38).png',
  'assets/stickers/milk&mocha/milk&mocha (39).png',
  'assets/stickers/milk&mocha/milk&mocha (4).png',
  'assets/stickers/milk&mocha/milk&mocha (40).png',
  'assets/stickers/milk&mocha/milk&mocha (5).png',
  'assets/stickers/milk&mocha/milk&mocha (6).png',
  'assets/stickers/milk&mocha/milk&mocha (7).png',
  'assets/stickers/milk&mocha/milk&mocha (8).png',
  'assets/stickers/milk&mocha/milk&mocha (9).png'
];

const mimi = [
  'assets/stickers/mimi/mimi1.gif',
  'assets/stickers/mimi/mimi2.gif',
  'assets/stickers/mimi/mimi3.gif',
  'assets/stickers/mimi/mimi4.gif',
  'assets/stickers/mimi/mimi5.gif',
  'assets/stickers/mimi/mimi6.gif',
  'assets/stickers/mimi/mimi7.gif',
  'assets/stickers/mimi/mimi8.gif',
  'assets/stickers/mimi/mimi9.gif'
];
